---
- name: Configure elk VM
  hosts: elkservers
  remote_user: sysadmin
  become: true
  tasks:

  - name: Install docker.io
    apt:
      name: docker.io
      state: present
      force_apt_get: yes
      update_cache: yes

  - name: Install python pip3
    apt:
      name: python3-pip
      state: present
      force_apt_get: yes

  - name: Install Docker Module
    pip:
      name: docker
      state: present

  - name: Increase virtual memory
    sysctl:
      name: vm.max_map_count
      value: "262144"
      state: present
      reload: yes

  - name: Install elk container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        -  5601:5601
        -  9200:9200
        -  5044:5044

  - name: enable docker services on startup
    systemd:
      name: docker
      enabled: yes
