---
- name: Install and configure Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
   
  - name: Install deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb
    
  - name: drop in metricbeat.yml 
    copy: 
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

  - name: start metricbeat service
    command: metricbeat -e

